newsAggregator/news/urls.py
from django.urls import path
from .views import scrape, news_list

app_name = 'news'
urlpatterns = [
  path('scrape/', scrape, name="scrape"),
  path('', news_list, name="home"),
]

newsAggregator/newsAggregator/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("news.urls")),
]

newsAggregator/news/models.py
from django.db import models

# Create your models here.


class Headline(models.Model):
    objects = None
    title = models.CharField(max_length=200)
    image = models.URLField(null=True, blank=True)
    url = models.TextField()

    def __str__(self):
        return self.title

newsAggregator/news/views.py
from django.shortcuts import render
import requests
from django.shortcuts import render, redirect
from bs4 import BeautifulSoup as BSoup
from .models import Headline
import requests
requests.packages.urllib3.disable_warnings()


# Create your views here.


def scrape(request):
    # Headline.objects.all().delete()
    session = requests.Session()
    session.headers = {"User-Agent": "Googlebot/2.1 (+http://www.google.com/bot.html)"}
    url = "https://www.myjoyonline.com/"
    content = session.get(url).content
    soup = BSoup(content, "html.parser")
    News = soup.find_all('div', {"class":"cw4lnv-11 dFCKPx"})
    for article in News:
        main = article.find_all('a',href=True)
        links = article.find('a', {"class":"sc-1out364-0 hMndXN js_link"})
        link = links['href']
        images = main[0].find('img',src=True)
        image_src = images['srcset'].split(" ")[-4]
        titles = article.find('h2', {"class":"sc-759qgu-0 cYlVdn cw4lnv-6 eXwNRE"})
        title = titles.text
        new_headline = Headline()
        new_headline.title = title
        new_headline.url = link
        new_headline.image = image_src
        new_headline.save()
    return redirect("../")


def news_list(request):
    headlines = Headline.objects.all()[::-1]
    context = {
        'object_list': headlines,
    }
    return render(request, "news/home.html", context)

newsAggregator/news/templates/news/home.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body style="background-color: black;">
    <div class="jumbotron" style="background-color: rgb(83, 81, 81);">
        <center><h1 style="color:black;font-weight: bold;font-size: 80px;">News Scraper</h1>
            <a href="{% url 'news:scrape' %}" class="btn btn-success" style="background-color: black;margin-top: 20px;width: 190px;height: 80px;font-weight: bold;font-size: 30px;padding: 10px;">Load news</a>
        </form>
    </center>
    </div>
  <div class="card-columns" style="padding: 10px; margin-left: 150px;margin-right: 10px;">
    {% for headline in headlines.all %}
    <div class="card" style="width: 18rem;border:5px white solid;margin-bottom: 50px;">
  <img class="card-img-top" src = "{{ headline.image }}">
  <div class="card-body">
    <h5 class="card-title"><div class="card-body">
      <a href="{{headline.url}}"><h5 class="card-title">{{headline.title}}</h5></a>
    </div></h5>
    </div>
  </div>
  {% endfor %}
</div>
</div>
    <script
src="http://code.jquery.com/jquery-3.3.1.min.js"
integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>